swagger: "2.0"

info:
  title: Perplexity MCP Connector
  version: "1.0"
  description: Server‑Sent Events endpoint that advertises MCP tools to Microsoft Copilot Studio.

# ─── CHANGE THIS ───────────────────────────────────────────────────────────
host: perplexmcpcopilot-gcaba9h2d5g6azfx.uksouth-01.azurewebsites.net
# ───────────────────────────────────────────────────────────────────────────
basePath: /
schemes:
  - https

# The stream is plain SSE; no JSON parsing.
produces:
  - text/event-stream

paths:
  /sse:
    get:
      x-ms-sse: true            # tells Power Platform this is a streaming op
      operationId: StreamSse
      summary: MCP SSE Stream
      description: >
        Returns the MCP tool list as a Server‑Sent Event and then closes.
        Copilot Studio re‑opens this endpoint whenever it needs updates.
      tags:
        - Agentic               # required for MCP
        - McpSse                # required for MCP
      parameters:
        - name: sessionId
          in: query
          type: string
          required: false
          description: Optional correlation ID
      responses:
        "200":
          description: Stream opened
          # (no schema block → runtime accepts raw text)

securityDefinitions: {}
security: []
