swagger: '2.0'
info:
  title: Perplexity MCP Connector
  version: '1.0'
  description: >-
    Server Sent Events endpoint that advertises MCP tools to Microsoft Copilot
    Studio.
host: perplexmcpcopilot-gcaba9h2d5g6azfx.uksouth-01.azurewebsites.net
basePath: /
schemes:
  - https
produces:
  - application/json
paths:
  /sse:
    get:
      x-ms-sse: true
      operationId: StreamSse
      summary: MCP SSE Stream
      description: Returns one Server Sent Event with the tool list, then closes.
      tags:
        - Agentic
        - McpSse
      parameters:
        - name: sessionId
          in: query
          type: string
          required: false
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: string
securityDefinitions: {}
security: []
x-ms-openai-manifest:
  humanName: Perplexity AI
  modelDescription: Perplexity AI
  contactEmail: graham@hosking.wales
  legalUrl: https://plex
