swagger: '2.0'
info:
  title: Perplexity MCP
  version: '1.0'
host: <your-app>.azurewebsites.net
basePath: /
schemes:
  - https
paths:
  /query:
    post:
      summary: Query Perplexity
      operationId: perplexity-search
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              prompt:
                type: string
              model:
                type: string
            required:
              - prompt
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              jsonrpc:
                type: string
              id:
                type: string
              result:
                type: object
                properties:
                  answer:
                    type: string
                  citations:
                    type: array
                    items: {}
