swagger: "2.0"
info:
  title: Perplexity MCP (MIN)
  version: "1.0"
  description: Minimal test spec for Copilot Studio MCP.
host: YOUR‑WEB‑APP.azurewebsites.net
basePath: /
schemes:
  - https
produces:
  - application/json           # Copilot Studio UI needs this
paths:
  /sse:
    get:
      x-ms-sse: true
      operationId: StreamSse
      summary: MCP SSE
      tags:
        - Agentic
        - McpSse
      responses:
        "200":
          description: OK
          schema:
            type: string        # simplest possible body
securityDefinitions: {}
security: []
